### ISSUE TITLE
Height of assembly

### ISSUE THREAD

**Issue by beniroquai** [openSIMMO/openSIMMO#1]
@ranranking what is the distance from the optical table to the port of the Nikon?

**Comment by ranranking** [comment]
I uploaded the measurement of the height. it should be 195mm according to the Nikon Adapter

**Comment by beniroquai** [comment]
That'S what I get from this "method" too :D 

![image](https://user-images.githubusercontent.com/4345528/163764842-329fb5d9-0777-434e-9e5f-f7eab7a9737d.png)
