### ISSUE TITLE
Open the holes for flex calbe and laser

### ISSUE THREAD

**Issue by ranranking** [openSIMMO/openSIMMO#10]
Laser should stay in the setup and only the cable out?

**Comment by beniroquai** [comment]
I'd say: In best case we have the FPC connect as the interface to the outside wall so that you only need to connect it. IF you have a fancy laser fom omicron you can use this, or you use the even more fancy one from Micost.

**Comment by beniroquai** [comment]
@ranranking  Did you add this to the laser cut assembly? ;)

**Comment by ranranking** [comment]
no, maybe i should add a hole on to the wall behind the laser driver, in order to make the other fiber laser acess to the inside.

**Comment by beniroquai** [comment]
Sounds like a good idea😛
